services:
    app:
        image: mylaravelapp:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        restart: always
        ports:
            - "9900:8000"
    mysql:
        image: mysql:latest
        ports:
            - '9999:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=zxc1337228
        volumes:
            - ./databases:/var/lib/mysql
